//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaba.Birthday.Reminder.Bot.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Answers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Answers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shaba.Birthday.Reminder.Bot.Services.Resources.Answers", typeof(Answers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕New event.
        /// </summary>
        internal static string AddNewEvent {
            get {
                return ResourceManager.GetString("AddNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose event for view detail information or click on button &quot;New event&quot;..
        /// </summary>
        internal static string ChooseEventForDetailsOrAddNew {
            get {
                return ResourceManager.GetString("ChooseEventForDetailsOrAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the desired button for action..
        /// </summary>
        internal static string ClickButtonForAction {
            get {
                return ResourceManager.GetString("ClickButtonForAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Delete.
        /// </summary>
        internal static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event: {0},
        ///Person: {1},
        ///Date: {2},
        ///Time: {3}..
        /// </summary>
        internal static string DetailedInfoAboutEvent {
            get {
                return ResourceManager.GetString("DetailedInfoAboutEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit date.
        /// </summary>
        internal static string EditDate {
            get {
                return ResourceManager.GetString("EditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️ Edit.
        /// </summary>
        internal static string EditEvent {
            get {
                return ResourceManager.GetString("EditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit event&apos;s name.
        /// </summary>
        internal static string EditName {
            get {
                return ResourceManager.GetString("EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit person.
        /// </summary>
        internal static string EditPerson {
            get {
                return ResourceManager.GetString("EditPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit time.
        /// </summary>
        internal static string EditTime {
            get {
                return ResourceManager.GetString("EditTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send contact for register you in our system:.
        /// </summary>
        internal static string EmptyPhoneNumber {
            get {
                return ResourceManager.GetString("EmptyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your location, for detection your time zone. We don&apos;t save or share your location:.
        /// </summary>
        internal static string EmptyTimeZone {
            get {
                return ResourceManager.GetString("EmptyTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event was successful added!.
        /// </summary>
        internal static string EventWasSuccessfulAdded {
            get {
                return ResourceManager.GetString("EventWasSuccessfulAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and I don&apos;t see date in your message, please try again. 
        ///Send date of event in next format: dd/mm/yyyy.
        /// </summary>
        internal static string IncorrectDateTryAgain {
            get {
                return ResourceManager.GetString("IncorrectDateTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and I don&apos;t see correct number in your message, please try again..
        /// </summary>
        internal static string IncorrectNumberOfEventTryAgain {
            get {
                return ResourceManager.GetString("IncorrectNumberOfEventTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened and I don&apos;t see time in your message, please try again.	
        ///Send time of event for remind you in next format: hh:mm.
        /// </summary>
        internal static string IncorrectTimeTryAgain {
            get {
                return ResourceManager.GetString("IncorrectTimeTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about event:
        ///.
        /// </summary>
        internal static string InfoAboutEvent {
            get {
                return ResourceManager.GetString("InfoAboutEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 Events.
        /// </summary>
        internal static string ListOfEvents {
            get {
                return ResourceManager.GetString("ListOfEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NonePerson {
            get {
                return ResourceManager.GetString("NonePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can create, view, delete and edit your events. On the keyboard in this chat, you can see the buttons. Click on the desired button for action..
        /// </summary>
        internal static string SendCommandForCreatingEvent {
            get {
                return ResourceManager.GetString("SendCommandForCreatingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send date of event in next format: dd/mm/yyyy.
        /// </summary>
        internal static string SendDateOfEvent {
            get {
                return ResourceManager.GetString("SendDateOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send name of event.
        /// </summary>
        internal static string SendNameOfEvent {
            get {
                return ResourceManager.GetString("SendNameOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send name of person or just click button &quot;None&quot;.
        /// </summary>
        internal static string SendNameOfPerson {
            get {
                return ResourceManager.GetString("SendNameOfPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send time of event for remind you in next format: hh:mm.
        /// </summary>
        internal static string SendTimeOfEvent {
            get {
                return ResourceManager.GetString("SendTimeOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📱 Send contact.
        /// </summary>
        internal static string SharePhoneNumber {
            get {
                return ResourceManager.GetString("SharePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗺️ Send location.
        /// </summary>
        internal static string ShareTimeZone {
            get {
                return ResourceManager.GetString("ShareTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}) Event: &quot;{1}&quot;. Date: {2}.
        /// </summary>
        internal static string StringBuilderList {
            get {
                return ResourceManager.GetString("StringBuilderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re successful registrated, {0}.
        ///You&apos;re time zone is {1} and current time is {2}
        ///.
        /// </summary>
        internal static string SuccessfulRegistration {
            get {
                return ResourceManager.GetString("SuccessfulRegistration", resourceCulture);
            }
        }
    }
}
