//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaba.Birthday.Reminder.Bot.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Answers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Answers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shaba.Birthday.Reminder.Bot.Services.Resources.Answers", typeof(Answers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕New event.
        /// </summary>
        internal static string AddNewEvent {
            get {
                return ResourceManager.GetString("AddNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Delete.
        /// </summary>
        internal static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️ Edit.
        /// </summary>
        internal static string EditEvent {
            get {
                return ResourceManager.GetString("EditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send contact for register you in our system:.
        /// </summary>
        internal static string EmptyPhoneNumber {
            get {
                return ResourceManager.GetString("EmptyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your location, for detection your time zone. We don&apos;t save or share your location:.
        /// </summary>
        internal static string EmptyTimeZone {
            get {
                return ResourceManager.GetString("EmptyTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 Events.
        /// </summary>
        internal static string ListOfEvents {
            get {
                return ResourceManager.GetString("ListOfEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can create, view, delete and edit your events. On the keyboard in this chat, you can see the buttons. Click on the desired button for action..
        /// </summary>
        internal static string SendCommandForCreatingEvent {
            get {
                return ResourceManager.GetString("SendCommandForCreatingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📱 Send contact.
        /// </summary>
        internal static string SharePhoneNumber {
            get {
                return ResourceManager.GetString("SharePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗺️ Send location.
        /// </summary>
        internal static string ShareTimeZone {
            get {
                return ResourceManager.GetString("ShareTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re successful registrated, {0}.
        ///You&apos;re time zone is {1} and current time is {2}
        ///.
        /// </summary>
        internal static string SuccessfulRegistration {
            get {
                return ResourceManager.GetString("SuccessfulRegistration", resourceCulture);
            }
        }
    }
}
